### ISSUE TITLE
Update Node.js and some dependencies

### ISSUE THREAD

**Issue by tobias-graf-p** [Stelzi79/action-minver#17]
Hi 

Is there any chance that this action will be updated in the near future? We use it in our workflows and (since a few weeks) notice the following issues:
- The `@actions/core` package should be updated to `v1.10.0` or greater to get the updated saveState and setOutput functions (see https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
- `Node.js` should be updated to `v16` in `action.yml`.

And also some other dependencies should be updated.

**Comment by Stelzi79** [comment]
I will look into the next few days when I have time. There are also a few PRs from dependabot to look at.

**Comment by tobias-graf-p** [comment]
@Stelzi79 Thank you for your reaction. Would really appreciate this! Would also offer to support you (in testing the new version of the action, e.g.).

Looking forward to hear again from you.

**Comment by tobias-graf-p** [comment]
@Stelzi79 Have you been able to look into upgrading the Github action?

**Comment by Stelzi79** [comment]
Yes I've looked into it. "Just" updating @actions/core package and similar GitHub-Actions related dependencies seem trivial at first glance. See PR https://github.com/Stelzi79/action-minver/pull/20 for progress on that front!

Considering that Node.JS is "only" used for internal tooling purpose of only compiling from TypeScript "source" file to native JavaScript files that the actions use I don't intend to maintain that Node.JS beyond what is in now. Dependabot is having a field day with only the tooling for "compiling" TypeScript to native JavaScript which is way beyond the use case and intended purpose and scope of JavaScript (in my opinion)! Especially the elevated "chatter" of dependabot surrounding updating Node.Js dependencies is a prime example for why you don't use Node.Js for such tooling tasks. In essence Node.js is JUST used to "compile" two .ts files to two .js files that the GitHub-Action file uses.

So going forward I will consider to move this action off of any Node.js tooling requirements! If and when I will go forwards with this will depend on demand of users of this action and the available time I have to do this change in tooling.

**Comment by Stelzi79** [comment]
I have released https://github.com/Stelzi79/action-minver/releases/tag/3.0.1 which updates dependencies. I hope this helps.

**Comment by tobias-graf-p** [comment]
Hi @Stelzi79 
Thank you very much for your responses!
I see that you updated a number of depencies. But the deprecation warnings in the Github workflows are not gone already (since you did not upgrade to @actions/core v1.10.0 and did not upgrade node.js. I didn't completely understand your justification for not upgrading node.js, but wouldn't this be as easy as configuring the version in the actions.yml file like here?

https://github.com/rubenesp87/semver-validation-action/pull/13/files

**Comment by Stelzi79** [comment]
Well I tried to upgrade to @actions/core v1.10.0 and it basically broke stuff. From what I glanced the needed work to move to that version is way more complicated than "just" updating the version in the dependencies.

The main issue I see with using the current structured GitHub-Action is that "only" 2 JavaScript files are doing the "translation-work" between the MinVer-cli and a useable GitHub-Action. In order to get to the 2 JavaScript files they are "originally" coded in TypeScript and all the "compiling" from TypeScript to JavaScript happens in a Yarp/Node.Js build environment beyond any GitHub-Action scope. Also the utility of having it in TypeScript instead of just plain (old) JavaScript is very minimal in my opinion.

I had a cursory look at the documentation of creating a dotnet-GitHubAction (https://learn.microsoft.com/en-us/dotnet/devops/create-dotnet-github-action) and it looks like that is a way better fit for using the dotnet tool MinVer as a single GitHub-Actions step for non dotnet projects build steps.

The next version of this action will be based on that approach so it makes little sense in investing resource into an ill fitting and over bloated structure.

**Comment by tobias-graf-p** [comment]
All right, I see.

That option to create dotnet Github action indeed looks very promising. Please let me know in case you would take more steps into this direction. On the other hand - if I find time - maybe I will give it a try myself and would also let you know.

**Comment by tobias-graf-p** [comment]
Link to discussion with maintainer of MinVer about an "official" Github action: https://github.com/adamralph/minver/discussions/850
